#!/bin/bash

module load gcc/10.2.0
module load cmake
module load cuda/11.1.1
module load spectrum-mpi
module load hdf5

#export PAMI_ENABLE_STRIPING=1
#export PAMI_IBV_ADAPTER_AFFINITY=1
#export PAMI_IBV_DEVICE_NAME="mlx5_0:1,mlx5_3:1"
#export PAMI_IBV_DEVICE_NAME_1="mlx5_3:1,mlx5_0:1"
